sudo: required
dist: trusty
language: php
php:
  - 5.6
  - 7.0
  - 7.1

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - docker
  - postgresql

env:
  global:
  - CORE_BRANCH=master
  matrix:
  - DB=sqlite

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"
  - "$HOME/.cache/bower"

before_install:
  - php --info
  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s nc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database nc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'nc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON nc_autotest.* TO 'nc_autotest'@'localhost';"; fi

  - npm install

  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - mv twofactor_u2f core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name nc_autotest --database-user nc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Set up app
  - php -f core/occ app:enable twofactor_u2f
  - cd core/apps/twofactor_u2f


script:
  # Check PHP syntax errors
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run server's app code checker
  #- php ../../occ app:check-code twofactor_u2f

  # Run JS tests
  - ./node_modules/karma/bin/karma start --single-run

  # Run PHP tests
  - cd tests
  - phpunit --configuration phpunit.xml

matrix:
  include:
    - php: 7
      env: "DB=sqlite CORE_BRANCH=stable11"
    - php: 5.6
      env: "DB=mysql"
    - php: 7.0
      env: "DB=pgsql"
  fast_finish: true
